# Generated by Django 3.2.16 on 2022-12-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('C', 'CashOnDelivery'), ('G', 'GooglePay'), ('P', 'PhonePay'), ('M', 'Paytm')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('F', 'Failed')], max_length=1, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
