# Generated by Django 4.1.2 on 2022-11-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('C', 'CashOnDelivery'), ('G', 'GooglePay'), ('P', 'PhonePay'), ('M', 'Paytm')], max_length=1, null=True),
        ),
    ]
