# Generated by Django 4.1.2 on 2022-11-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='twitter_handle',
        ),
    ]
