# Generated by Django 4.1.2 on 2022-11-27 06:47

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
    ]
