# Generated by Django 4.1.2 on 2022-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
