# Generated by Django 4.1.2 on 2022-11-27 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.TimeField(null=True, verbose_name='time placed')),
                ('is_ready', models.BooleanField(default=False, null=True)),
                ('order_for', models.CharField(max_length=50, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('F', 'Failed')], max_length=1, null=True)),
                ('food_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
