# Generated by Django 3.2.16 on 2022-12-28 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.TimeField(null=True, verbose_name='time placed')),
                ('is_ready', models.BooleanField(default=False, null=True)),
                ('order_for', models.CharField(max_length=50, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('instructions', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('P', 'Pending'), ('F', 'Failed')], max_length=1, null=True)),
                ('food_items', models.ManyToManyField(to='food.Food')),
            ],
        ),
    ]
