# Generated by Django 4.1.2 on 2022-11-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryPartner', '0001_initial'),
        ('order', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_handled_deliveryPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeliveryPartner.profile'),
        ),
    ]
