# Generated by Django 4.1.2 on 2022-11-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_handled_deliverypartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_handled_deliveryPartner',
        ),
    ]
